### ISSUE TITLE
Unable to register - expired certificate

### ISSUE THREAD

**Issue by moneytoo** [WhisperSystems/RedPhone#415]
I'm unable to register on android:

```
07-14 10:40:42.412   8585-13793/? W/RegistrationService﹕ org.thoughtcrime.redphone.signaling.SignalingException: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
            at org.thoughtcrime.redphone.signaling.SignalingSocket.constructSSLSocket(SignalingSocket.java:144)
            at org.thoughtcrime.redphone.signaling.SignalingSocket.<init>(SignalingSocket.java:112)
            at org.thoughtcrime.redphone.signaling.AccountCreationSocket.<init>(AccountCreationSocket.java:39)
            at org.thoughtcrime.redphone.registration.RegistrationService.handleRegistrationIntent(RegistrationService.java:193)
            at org.thoughtcrime.redphone.registration.RegistrationService.access$000(RegistrationService.java:52)
            at org.thoughtcrime.redphone.registration.RegistrationService$1.run(RegistrationService.java:87)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
            at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
            at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:93)
            at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:388)
            at org.thoughtcrime.redphone.signaling.SignalingSocket.timeoutHackConnect(SignalingSocket.java:170)
            at org.thoughtcrime.redphone.signaling.SignalingSocket.constructSSLSocket(SignalingSocket.java:142)
            at org.thoughtcrime.redphone.signaling.SignalingSocket.<init>(SignalingSocket.java:112)
            at org.thoughtcrime.redphone.signaling.AccountCreationSocket.<init>(AccountCreationSocket.java:39)
            at org.thoughtcrime.redphone.registration.RegistrationService.handleRegistrationIntent(RegistrationService.java:193)
            at org.thoughtcrime.redphone.registration.RegistrationService.access$000(RegistrationService.java:52)
            at org.thoughtcrime.redphone.registration.RegistrationService$1.run(RegistrationService.java:87)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

Checking cert with ``openssl s_client -showcerts -connect master.whispersystems.org:31337`` I noticed it expires today (2015-07-14 9:14:59) which is probably the reason for the issue.

**Comment by peterpanondrugs** [comment]
Same here, network failure! Multiple devices which were registered arent working anymore, and cant register anymore.

**Comment by zerokes** [comment]
Same with calls, SSL exception from expired certificate:
`W/InitiatingCallManager( 4007): org.thoughtcrime.redphone.signaling.SignalingException: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
W/InitiatingCallManager( 4007): 	at org.thoughtcrime.redphone.signaling.SignalingSocket.constructSSLSocket(SignalingSocket.java:144)
W/InitiatingCallManager( 4007): 	at org.thoughtcrime.redphone.signaling.SignalingSocket.<init>(SignalingSocket.java:112)
W/InitiatingCallManager( 4007): 	at org.thoughtcrime.redphone.call.InitiatingCallManager.run(InitiatingCallManager.java:80)
W/InitiatingCallManager( 4007): Caused by: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate
W/InitiatingCallManager( 4007): 	at com.android.org.conscrypt.SSLNullSession.getPeerCertificates(SSLNullSession.java:104)
W/InitiatingCallManager( 4007): 	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:98)
W/InitiatingCallManager( 4007): 	at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:393)
W/InitiatingCallManager( 4007): 	at org.thoughtcrime.redphone.signaling.SignalingSocket.timeoutHackConnect(SignalingSocket.java:170)
W/InitiatingCallManager( 4007): 	at org.thoughtcrime.redphone.signaling.SignalingSocket.constructSSLSocket(SignalingSocket.java:142)`

Command to check notAfter (seems moneytoo cmd got cut): 
`openssl s_client -showcerts -connect master.whispersystems.org:31337 | openssl x509 -noout -dates`
