### ISSUE TITLE
Cannot Ring through to phone which recently changed IP#

### ISSUE THREAD

**Issue by bboerner** [WhisperSystems/RedPhone#419]
I have been testing RedPhone with two devices - ZTE Zinger and BLU Dash C Music. This is to report a very reliable test case where a calling RedPhone will not reach another RedPhone.

All phones are connected using WiFi.

The problem seems to be when the IP# of the device changes (by initiating or disconnecting a VPN session) that for some period of time (sometimes minutes, sometimes more than 10 minutes) the calling phone will display "Dialing..." and *never* transition to "Ringing...".

Using debug logs (which I'll attach) I see for the success case (call rings through to the other end):

```
...
W/RedPhone(18328): Binding to RedPhoneService...
W/RedPhone(18328): Got message from service: 12
W/RedPhone(18328): Got message from service: 7
W/RedPhone(18328): Got message from service: 3
W/RedPhone(18328): Got message from service: 0
W/RedPhone(18328): Hangup pressed, handling termination now...
...
```

While for the unsuccessful case (call does not transition from "Dialing..." to "Ringing..."):

```
...
W/RedPhone(18328): Binding to RedPhoneService...
W/RedPhone(18328): Got message from service: 12
W/RedPhone(18328): Hangup pressed, handling termination now...
...
```

To reproduce:

1. Assume phone A and phone B. Assume they can successfully call each other.
1. On phone B initiate a VPN connection thus changing its IP address.
1. Use Phone B to dial Phone A. Status is "Dialing...", then transitions to "Ringing..." and call is successful. This shows that calling from the device with changed IP# to device with unchanged IP# works.
1. Use Phone A to dial Phone B. Status is "Dialing..." and never transitions to "Ringing..."
1. Wait for up to 10+ minutes.
1. Again use Phone A to dial Phone B. Status is "Dialing...", then transitions to "Ringing..." and call is successful.
1. Disconnect VPN session on phone B thus the IP address changes.
1. Again use Phone A to dial Phone B. Status is "Dialing..." and never transitions to "Ringing..."
1. Wait for up to 10+ minutes.
1. Again use Phone A to dial Phone B. Status is "Dialing...", then transitions to "Ringing..." and call is successful.

**Comment by bboerner** [comment]
Ah, I didn't realize github doesn't allow attachments so I'll put the debug logs here.

Only Dials, never rings:

```
W/RedPhoneService(18328): Received Intent: org.thoughtcrime.redphone.RedPhoneService.OUTGOING_CALL
W/RedPhone(18328): Binding to RedPhoneService...
W/RedPhone(18328): Got message from service: 12
W/RedPhone(18328): Hangup pressed, handling termination now...
W/RedPhone(18328): handleTerminate called
W/RedPhone(18328): Termination Stack:
W/RedPhone(18328): java.lang.Exception
W/RedPhone(18328): 	at org.thoughtcrime.redphone.RedPhone.handleTerminate(RedPhone.java:238)
W/RedPhone(18328): 	at org.thoughtcrime.redphone.RedPhone.access$600(RedPhone.java:67)
W/RedPhone(18328): 	at org.thoughtcrime.redphone.RedPhone$HangupButtonListener.onClick(RedPhone.java:432)
W/RedPhone(18328): 	at org.thoughtcrime.redphone.ui.CallControls$3.onClick(CallControls.java:152)
W/RedPhone(18328): 	at android.view.View.performClick(View.java:4438)
W/RedPhone(18328): 	at android.view.View$PerformClick.run(View.java:18423)
W/RedPhone(18328): 	at android.os.Handler.handleCallback(Handler.java:733)
W/RedPhone(18328): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/RedPhone(18328): 	at android.os.Looper.loop(Looper.java:136)
W/RedPhone(18328): 	at android.app.ActivityThread.main(ActivityThread.java:5050)
W/RedPhone(18328): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/RedPhone(18328): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/RedPhone(18328): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
W/RedPhone(18328): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
W/RedPhone(18328): 	at dalvik.system.NativeStart.main(Native Method)
W/RedPhoneService(18328): Received Intent: org.thoughtcrime.redphone.RedPhoneService.HANGUP
W/RedPhoneService(18328): termination stack
W/RedPhoneService(18328): java.lang.Exception
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.terminate(RedPhoneService.java:362)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.handleHangupCall(RedPhoneService.java:268)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.onIntentReceived(RedPhoneService.java:149)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.access$200(RedPhoneService.java:75)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService$IntentRunnable.run(RedPhoneService.java:567)
W/RedPhoneService(18328): 	at java.lang.Thread.run(Thread.java:841)
```

Dials and Rings through:
```
W/RedPhone(18328): Binding to RedPhoneService...
W/RedPhone(18328): Got message from service: 7
W/RedPhone(18328): Got message from service: 6
W/RedPhone(18328): handleTerminate called
W/RedPhone(18328): Termination Stack:
W/RedPhone(18328): java.lang.Exception
W/RedPhone(18328): 	at org.thoughtcrime.redphone.RedPhone.handleTerminate(RedPhone.java:238)
W/RedPhone(18328): 	at org.thoughtcrime.redphone.RedPhone.access$600(RedPhone.java:67)
W/RedPhone(18328): 	at org.thoughtcrime.redphone.RedPhone$CallStateHandler.handleMessage(RedPhone.java:402)
W/RedPhone(18328): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/RedPhone(18328): 	at android.os.Looper.loop(Looper.java:136)
W/RedPhone(18328): 	at android.app.ActivityThread.main(ActivityThread.java:5050)
W/RedPhone(18328): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/RedPhone(18328): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/RedPhone(18328): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
W/RedPhone(18328): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
W/RedPhone(18328): 	at dalvik.system.NativeStart.main(Native Method)
W/RedPhoneService(18328): termination stack
W/RedPhoneService(18328): java.lang.Exception
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.terminate(RedPhoneService.java:362)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.notifyCallDisconnected(RedPhoneService.java:468)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.call.SignalManager$SignalListenerTask.run(SignalManager.java:80)
W/RedPhoneService(18328): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/RedPhoneService(18328): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/RedPhoneService(18328): 	at java.lang.Thread.run(Thread.java:841)
W/RedPhoneService(18328): Received Intent: org.thoughtcrime.redphone.RedPhoneService.OUTGOING_CALL
W/RedPhone(18328): Binding to RedPhoneService...
W/RedPhone(18328): Got message from service: 12
W/RedPhone(18328): Got message from service: 7
W/RedPhone(18328): Got message from service: 3
W/RedPhone(18328): Got message from service: 0
W/RedPhone(18328): Hangup pressed, handling termination now...
W/RedPhone(18328): handleTerminate called
W/RedPhone(18328): Termination Stack:
W/RedPhone(18328): java.lang.Exception
W/RedPhone(18328): 	at org.thoughtcrime.redphone.RedPhone.handleTerminate(RedPhone.java:238)
W/RedPhone(18328): 	at org.thoughtcrime.redphone.RedPhone.access$600(RedPhone.java:67)
W/RedPhone(18328): 	at org.thoughtcrime.redphone.RedPhone$HangupButtonListener.onClick(RedPhone.java:432)
W/RedPhone(18328): 	at org.thoughtcrime.redphone.ui.CallControls$3.onClick(CallControls.java:152)
W/RedPhone(18328): 	at android.view.View.performClick(View.java:4438)
W/RedPhone(18328): 	at android.view.View$PerformClick.run(View.java:18423)
W/RedPhone(18328): 	at android.os.Handler.handleCallback(Handler.java:733)
W/RedPhone(18328): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/RedPhone(18328): 	at android.os.Looper.loop(Looper.java:136)
W/RedPhone(18328): 	at android.app.ActivityThread.main(ActivityThread.java:5050)
W/RedPhone(18328): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/RedPhone(18328): 	at java.lang.reflect.Method.invoke(Method.java:515)
W/RedPhone(18328): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
W/RedPhone(18328): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
W/RedPhone(18328): 	at dalvik.system.NativeStart.main(Native Method)
W/RedPhoneService(18328): Received Intent: org.thoughtcrime.redphone.RedPhoneService.HANGUP
W/RedPhoneService(18328): termination stack
W/RedPhoneService(18328): java.lang.Exception
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.terminate(RedPhoneService.java:362)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.handleHangupCall(RedPhoneService.java:268)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.onIntentReceived(RedPhoneService.java:149)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService.access$200(RedPhoneService.java:75)
W/RedPhoneService(18328): 	at org.thoughtcrime.redphone.RedPhoneService$IntentRunnable.run(RedPhoneService.java:567)
W/RedPhoneService(18328): 	at java.lang.Thread.run(Thread.java:841)
```
